### ISSUE TITLE
nginx default config file

### ISSUE THREAD

**Issue by yefriddavid** [joselfonseca/docker-nginx-php-7#1]
hay un pequeño error en el archivo default en la linea 9 (try_files $uri $uri/ /index.php?\$query_string;)
remplazarla por (try_files $uri $uri/ /index.php?$query_string;)

**Comment by joselfonseca** [comment]
Gracias por el issue, estoy teniendo un poco de problema entendiendo lo que quiere decir, las 2 lineas que me menciona son exactamente iguales.
```
(try_files $uri $uri/ /index.php?$query_string;)
(try_files $uri $uri/ /index.php?$query_string;)
```
Podría por favor ser un poco mas especifico sobre el problema / error ? 

Muchas Gracias.

**Comment by yefriddavid** [comment]
El problema puntual es el backslash que hay antes del $, 

try_files $uri $uri/ /index.php?\$query_string;)

Cuando hago post me llega ese dato al servidor como un campo asi [\\]

Laravel lo toma como una campo querystring

**Comment by yefriddavid** [comment]
try_files $uri $uri/ /index.php?\\$query_string;) asi lo tienes, github lo remueve

**Comment by yefriddavid** [comment]
Al servidor llega algo como esto [\\\=>``] ese backslash lo toma como querysteing parameter

**Comment by joselfonseca** [comment]
Good catch! no lo me había dado cuenta.

**Comment by joselfonseca** [comment]
Imagen actualizada https://hub.docker.com/r/joselfonsecadt/nginx-php7.0/tags/
